const sentences = ["The quick brown fox jumps over the lazy dog.",
    "The rain in Spain falls mainly on the plain.",
    "To be or not to be, that is the question.",
    "I am the walrus, goo goo g'joob.",
    "Do not go gentle into that good night.",
    "The great Gatsby was a book about a man named Gatsby.",
    "The cat in the hat came back.",
    "A tale told by an idiot, full of sound and fury, signifying nothing.",
    "The quick brown fox jumps over the lazy dog again.",
    "The rain in Spain still falls mainly on the plain.",
    "To be or not to be, that is still the question.",
    "I am still the walrus, goo goo g'joob.",
    "Do not go gentle into that good night, rage, rage against the dying of the light.",
    "The great Gatsby was a book about a man named Gatsby, who threw lavish parties and had a mysterious past.",
    "The cat in the hat came back, but this time he brought his friends.",
    "A tale told by an idiot, full of sound and fury, still signifying nothing.",
    "The quick brown fox jumps over the lazy dog yet again.",
    "The rain in Spain continues to fall mainly on the plain.",
    "To be or not to be, that is still the eternal question.",
    "I am still the walrus, goo goo g'joob, koo koo ca choo.",
    "Do not go gentle into that good night, old age should burn and rave at close of day.",
    "The great Gatsby was a book about a man named Gatsby, who had a tumultuous relationship with a woman named Daisy.",
    "The cat in the hat came back, bringing even more chaos and mischief with him.",
    "A tale told by an idiot, full of sound and fury, yet still signifying nothing.",
    "The quick brown fox jumps over the lazy dog yet again and again.",
    "The rain in Spain persists in falling mainly on the plain.",
    "To be or not to be, that is still the age-old question.",
    "I am still the walrus, goo goo g'joob, koo koo ca choo, la la la la.",
    "Do not go gentle into that good night, rage, rage against the dying of the light.",
    "The great Gatsby was a book about a man named Gatsby, who lived a lavish lifestyle and had a mysterious past.",
    "The cat in the hat came back, bringing even more mischief and chaos with him.",
    "A tale told by an idiot, full of sound and fury, still signifying nothing.",
    "The quick brown fox jumps over the lazy dog yet again and again and again.",
    "The rain in Spain continues to fall mainly on the plain.",
    "To be or not to be, that is still the age-old question that plagues us all.",
    "I am still the walrus, goo goo g'joob, koo koo ca choo, la la la la, tee tee tee.",
    "Do not go gentle into that good night, rage, rage against the dying of the light.",
];